# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('option1', models.CharField(max_length=240)),
                ('option2', models.CharField(max_length=240)),
                ('option3', models.CharField(max_length=240)),
                ('option4', models.CharField(max_length=240)),
            ],
        ),
    ]
