# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('option1', models.CharField(max_length=240)),
                ('option2', models.CharField(max_length=240)),
                ('option3', models.CharField(max_length=240)),
                ('option4', models.CharField(max_length=240)),
                ('url', models.CharField(blank=True, default=None, max_length=240)),
                ('answer', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=5)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuestionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.UserModel')),
            ],
        ),
    ]
