# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionServed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuestionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.UserModel')),
            ],
        ),
    ]
