# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_questionserved_is_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuestionModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionserved',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionserved',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionServed',
        ),
    ]
