# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_usermodel_count'),
        ('Quiz', '0004_auto_20170708_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuestionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.UserModel')),
            ],
        ),
    ]
